channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterhub-singleuser>=3.0,<4.0

  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # Install packages from pip
  - pip
  - pip:
    - otter-grader
    - datascience
    - plotly
